### ISSUE TITLE
Allow supplying a base DO so you can define alarm methods etc.

### ISSUE THREAD

**Issue by johtso** [markusahlstrand/trpc-durable-objects#1]
Firstly, super excited about this project! Proper type safe RPC access to DOs from workers would be absolute magic.

Currently createProxy is responsible for defining the DO class. This means you can't define an alarm method.

Would an easy solution maybe just be to take an optional argument of a DO class and subclass it if provided?

**Comment by markusahlstrand** [comment]
Thanks for the issue! 

I tried adding a function as a second parameter as you suggested and it seems to work just fine. I'll post a new version for it.

**Comment by markusahlstrand** [comment]
Pushed version 1.1.0 and some update to the docs for how it works :)
